import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "React Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>  
    
      <html lang="en">
        <body
          className={`w-full h-screen antialiased`}
        >
          {children}
        </body>
      </html>
    </>
  );
}
